### ISSUE TITLE
Import Kite Error

### ISSUE THREAD

**Issue by seiswang** [pyrocko/kite#106]
ImportError: cannot import name 'covariance_ext' from partially initialized module 'kite' (most likely due to a circular import) (/home/oem/src/kite/kite/__init__.py)

**Comment by miili** [comment]
When installing from pypi this should not be a problem. Running inside the kite directory is of course possible. In dededicated development mode.

**Comment by 1973389460** [comment]
![e03908d9a17cfe3417ee2b1ca51aaf1c](https://github.com/pyrocko/kite/assets/114404859/d97c5730-0239-4583-8794-dfaaff60b0eb)
I have the same problem

**Comment by 1973389460** [comment]
what should I do

**Comment by hvasbath** [comment]
Please see here: https://github.com/pyrocko/kite/issues/113
