### ISSUE TITLE
circular import issue

### ISSUE THREAD

**Issue by hvasbath** [pyrocko/kite#113]
meysam on pyrocko support, installation channel

```
Hi, I wanted to update the Pyrocko and Kite, and I am facing this error. I wonder if anyone knows the reason for that? 
Traceback (most recent call last):
  File "/home/geodesy/anaconda3/envs/TEST_kite/bin/spool", line 5, in <module>
    from kite.spool.main import main
  File "/home/geodesy/anaconda3/envs/TEST_kite/lib/python3.9/site-packages/kite/init.py", line 4, in <module>
    from .covariance import Covariance  # noqa
  File "/home/geodesy/anaconda3/envs/TEST_kite/lib/python3.9/site-packages/kite/covariance.py", line 18, in <module>
    from kite import covariance_ext
ImportError: cannot import name 'covariance_ext' from partially initialized module 'kite' (most likely due to a circular import) (/home/geodesy/anaconda3/envs/TEST_kite/lib/python3.9/site-packages/kite/init.py)
```

**Comment by hvasbath** [comment]
Might be related:
https://github.com/pyrocko/kite/commit/3f06670d8c6da9318859be7db40b07d4956b92f7

**Comment by Uncleyyyyy** [comment]
So if there is any solution now?

**Comment by emolch** [comment]
Have run into this several times with different setups. How exactly did you install kite? From source or using the pip package? Are you using the latest version? The latest commits on master try to resolve this issue.

**Comment by hvasbath** [comment]
I just did a fresh install ubuntu 20.04, python11 venv environment with the pip and I have no issues.
@Uncleyyyyy do you also have the issue? What are your system specs?

**Comment by Suansuan0922** [comment]
I have the same error, is there any solution?

**Comment by hvasbath** [comment]
Hello @Suansuan0922 can you please provide your installation details?! Meysam (initial issue reporter) was meanwhile able to install it falling back to the latest released version (pip install kite) instead of the latest version on master (pip install .  (in the source directory)).

**Comment by Uncleyyyyy** [comment]
> I just did a fresh install ubuntu 20.04, python11 venv environment with the pip-meaning this does not include the latest installation patch and I have no issues. @Uncleyyyyy do you also have the issue? What are your system specs?

I was also using 
/pip install kite
to install kite on my ubuntu 20.04. And my python version was pyhon3.8 in a virtual environment created by anaconda in order to use BEAT.

**Comment by Uncleyyyyy** [comment]
> The install instructions on the website need updating. They suggest to install from source. But the standard way should be to install latest stable release, i.e. with:
> 
> ```
> pip install kite
> ```

And the error reported as below:
`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/uncley/anaconda3/envs/beat/lib/python3.8/site-packages/kite/__init__.py", line 4, in <module>
    from .covariance import Covariance  # noqa
  File "/home/uncley/anaconda3/envs/beat/lib/python3.8/site-packages/kite/covariance.py", line 18, in <module>
    from kite import covariance_ext
ImportError: cannot import name 'covariance_ext' from partially initialized module 'kite' (most likely due to a circular import) (/home/uncley/anaconda3/envs/beat/lib/python3.8/site-packages/kite/__init__.py)
`

**Comment by emolch** [comment]
I added some compatibility fixes in the branch `bugfix/compatibility`, please check if this solves the issues.

**Comment by auld-L** [comment]
I install kite with anaconda，i can't find the setup.py ,what should i do?
