### ISSUE TITLE
kite start 

### ISSUE THREAD

**Issue by auld-L** [pyrocko/kite#118]
When I run this script，
![b2bac839a371f2e7b8c3ad74688e99c1](https://github.com/pyrocko/kite/assets/114404859/e6cfccfc-b78d-4a15-a79d-2ede0ab4929d)
it always enter the inter
![e911940b22778e07a4a0ed98dad2b87a](https://github.com/pyrocko/kite/assets/114404859/24e85608-39ca-4e3a-b2a5-0563743f2dcb)
how can i solve this problem？

**Comment by auld-L** [comment]
![lQLPJyHe-HgYnvN5zQOhsHvwcyYzgEAcBXxlgapHGQA_929_121](https://github.com/pyrocko/kite/assets/114404859/085a706b-0b5f-4d52-9f8a-12a5143cedd9)

**Comment by miili** [comment]
Remove the escaping slashes.

**Comment by auld-L** [comment]
if not have the \ ,my computer cannot recognize the ()，the slashes is not real problem.
![1c01a293f4699fe085006a475c0f03ce](https://github.com/pyrocko/kite/assets/114404859/30827477-9334-4c02-8748-a20c1c6fcf42)

**Comment by hvasbath** [comment]
This is a PYTHON! script not bash!
```
python 1.py
```
