### ISSUE TITLE
Covariance : Singular Matrix while loading scene

### ISSUE THREAD

**Issue by SonicxPrime** [pyrocko/kite#122]
Hi everyone,

We are trying to import SNAP tif result into Kite. At the moment, we don't have the [NEU].tif file. We don't know how to do it yet in SNAP. Any idea is welcome.

First, while loading the tif file in Kite, it is complaining about Covariance : Singular Matrix:
![Kite_Error](https://github.com/pyrocko/kite/assets/12641070/455e50f2-2842-45ee-8541-90ec42b94522)

Another error is while going in the Scene.APS tab, it is complainign about the **_AttributeError: module 'pyrocko.dataset.topo.srtmgl3' has no attribute 'covers'_**:
![srtmgl3](https://github.com/pyrocko/kite/assets/12641070/36831596-a6cd-4937-af41-569751da364f)

Sincerely,
Tahina

**Comment by hvasbath** [comment]
Dear Tahina,

unfortunately, for now KITE does not have functionality for the import of data processed with SNAP. You would need to extend the scene_io.py module with a SNAP class. https://pyrocko.org/kite/docs/current/reference/kite.scene.html#module-kite.scene_io

As far as I am aware no one from the current developer team will have time to implement that, but we may find time to guide you in case you want to give it a shot.

Best regards,
Hannes

**Comment by SonicxPrime** [comment]
Dear Hannes,

Thank you for your response.
Yes, i would like to try that solution if you can guide me.

Best regards,
Tahina

**Comment by hvasbath** [comment]
Hi again,
I just vaguely remembered that there may be this option in SNAP to export your file to GAMMA format. Can you check please? Then you could use this as a workaround, because GAMMA format is supported by KITE. One thing that I can see from the image above is that you need to make sure that your pixels that have no-data should be of NaN value, not zero as above. Thats also why the singular matrix occurs. But this zero assignment to pixels is likely the result of the misinterpretation of the data.

If that does not work we will likely need to find a time slot that works for both of us to meet via zoom/skype/itsi whatever is available to you to discuss the roadmap for implementation.

Cheers!
Hannes

**Comment by hvasbath** [comment]
The file .par is the parameter file not the image. So you need to try to load the exported image data. See here for expected inputs: https://pyrocko.org/kite/docs/current/reference/kite.scene.html#kite.scene_io.Gamma

**Comment by SonicxPrime** [comment]
I have all the files here:
![Screenshot from 2024-02-22 09-30-55](https://github.com/pyrocko/kite/assets/12641070/355fa606-fe87-4d6f-bedd-00c5c033638d)

**Comment by hvasbath** [comment]
Incidence angle files need to be named *phi* and *theta*, then
spool --load=displacement_VV.rslc may work, however, I would not expect the unwrapped geocoded displacement map to be be a complex image as suggested by the .rslc ending. You cannot import wrapped interferograms, but unwrapped displacements which should be only of float format.

**Comment by SonicxPrime** [comment]
Following your advice. I still get the error here:
![Screenshot from 2024-02-22 10-45-33](https://github.com/pyrocko/kite/assets/12641070/263847df-f3b2-4ed2-8b58-43ba9e53b7f7)

**Comment by hvasbath** [comment]
I was successful importing my own data following the export to gamma format from SNAP. Likely you are missing files, you need to make sure to create them beforehand in your data container within snap.
![Screenshot from 2024-02-22 13-38-56](https://github.com/pyrocko/kite/assets/11273616/4eef474a-ca63-45b9-8117-1724a51a5a45)

**Comment by SonicxPrime** [comment]
Dear Hannes,

I applied the Terrain correction from the Unwrapped data. I still have this. Maybe still have missing files?

![Screenshot from 2024-02-23 07-10-15](https://github.com/pyrocko/kite/assets/12641070/f2fd2ac4-ea4d-40bc-b67d-d57ad443eafc)


Best regards,
Tahina

**Comment by hvasbath** [comment]
the abstracted metadata file is needed

**Comment by SonicxPrime** [comment]
Wow! It's working. Many thanks. But there is still this one problem about **AttributeError: module 'pyrocko.dataset.topo.srtmgl3' has no attribute 'covers'** while going through Scene.APS:

![Screenshot from 2024-02-23 07-57-25](https://github.com/pyrocko/kite/assets/12641070/1b4966e0-92b9-449d-bc84-f4bfd629f057)

![Screenshot from 2024-02-23 07-57-15](https://github.com/pyrocko/kite/assets/12641070/9707178d-281c-4cd3-ab07-75fcc94ba0eb)

![Screenshot from 2024-02-23 07-58-17](https://github.com/pyrocko/kite/assets/12641070/e60c28fe-73f3-4579-a781-cfce74fd8908)


Best regards,
Tahina

**Comment by emolch** [comment]
Sorry, that one's my fault.  It is due to a recent change in Pyrocko. I will provide a fix.

**Comment by SonicxPrime** [comment]
Ok. Great

**Comment by SonicxPrime** [comment]
Dear Sebastian,

I upgraded kite to 1.5.8 and It is working now.

![Screenshot from 2024-03-12 09-23-55](https://github.com/pyrocko/kite/assets/12641070/77adaea5-babb-4475-b68f-c984e23679df)

Many thanks.

Best regards,
Tahina
