### ISSUE TITLE
Request for example files

### ISSUE THREAD

**Issue by mohseniaref** [pyrocko/kite#18]
Dear all,

I am looking for example dataset in Kite.Would you please inform me how I can find for instance dataset.mat or unwrap_ll.grd?
I found the example in http://data.pyrocko.org/testing/kite/ 

Best Regards,
MMA

**Comment by miili** [comment]
Hi Mohammad,

sry for not replying earlier. So yes: the testing datasets can be found at that address.
A link to that repository should go into the documentation.

The software is still in development, if you have find bugs, have questions or ideas, please don't hesitate to write an issue here.

best,

Marius
