### ISSUE TITLE
installation error of kite

### ISSUE THREAD

**Issue by kpsanjay** [pyrocko/kite#23]
i am getting following error while excuting the below command

```
sudo python3 setup.py install

building 'covariance_ext' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.4m -c src/ext/covariance.c -o build/temp.linux-x86_64-3.4/src/ext/covariance.o -fopenmp
src/ext/covariance.c:5:20: fatal error: Python.h: No such file or directory
 #include "Python.h"
                    ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by miili** [comment]
Sorry for the late reply, the holidays are just over.

You have to install the python  development files in apt it is 
the package `python-dev`.
The `master` release is not compatible with python 3. So you want to use python2 for it. However there is a working python3 branch you could also install.

**Comment by kpsanjay** [comment]
Thanks i have successfully install.
Pl help in executing the code.
should i write the python script to import the scene?
i tried with the test example as given  (pyqtgraph/kite/test).
i executed the test_scence.py program.

sanjay@SanjayNCS:~/pyqtgraph/kite/test$ python test_scene.py 
Traceback (most recent call last):
  File "test_scene.py", line 4, in <module>
    from kite import TestScene
  File "/usr/local/lib/python2.7/dist-packages/kite-2017.11-py2.7-linux-x86_64.egg/kite/__init__.py", line 4, in <module>
    from .scene import Scene, TestScene, read  # noqa
  File "/usr/local/lib/python2.7/dist-packages/kite-2017.11-py2.7-linux-x86_64.egg/kite/scene.py", line 8, in <module>
    from pyrocko import guts
  File "/usr/local/lib/python2.7/dist-packages/pyrocko-2017.11.22-py2.7-linux-x86_64.egg/pyrocko/guts.py", line 7, in <module>
    from builtins import str as newstr
ImportError: No module named builtins

But getting error.
Please let me know how to import the scene?
Regards
sanjay

**Comment by emolch** [comment]
hi, this might indicate, that the `python-future` package is not installed.

**Comment by kpsanjay** [comment]
hi i just install future. still following error occured.
Sanjay@SanjayNCS:~/pyqtgraph/kite/test$ python test_scene.py 
/usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "test_scene.py", line 6, in <module>
    from . import common
ValueError: Attempted relative import in non-package

**Comment by kpsanjay** [comment]
Hi all kite user,
Please let me know how to import unwrap grid file.
i am not good in python. so pl explain how i have to execute to kite .
Sanjay
