### ISSUE TITLE
Kite Installation

### ISSUE THREAD

**Issue by Wilhelm-Berrocal** [pyrocko/kite#27]
Hello there! I have a little trouble trying to install Kite, so I installed kite using pip with:

`sudo pip install git+https://github.com/pyrocko/kite.git`

Apparently everything worked fine as we can see here: 

![screenshot](https://user-images.githubusercontent.com/8532837/40745379-f0dda72e-641c-11e8-9c27-687e53d1b100.png)

But when I try to call kite, i get the infamous error `No module named 'kite'` I suppose it has to do with the `PATHS` but I don´t know, all suggestions are welcome.

Thanks a lot!

**Comment by hvasbath** [comment]
As you can see from the installation prompt. Kite got installed into the python2.7 packages.
However, when you start your python it starts python3. So when you start a python2 session- I guess that would work with "python2" instead of "python", you should be able to import kite.

**Comment by hsudha** [comment]
Hi, our newest "kite" version and the one that we will keep maintained is at the moment not the master, but the "python3" branch. Best is you clone kite from github and then do (seeing that your default python is already python3):
```
cd kite
git checkout origin python3
sudo python setup.py install
```
You will need to use "pip3" for the pyqtgraph, too. Also you need `pyrocko` in your python3 packages. The `pyrocko` master works for python2 and python3.
Good luck!

**Comment by Wilhelm-Berrocal** [comment]
Hello to everyone and thank you for your time and answers, I tried @hvasbath answer which suggested to use python2 to no avail, I have the same `ImportError: No module named kite` error as before, this makes me think that my installation of kite is flawed, 

![scrot1](https://user-images.githubusercontent.com/8532837/40788134-f2495ee4-64b4-11e8-963c-122908f56243.png)


I will try @hsudha answer of installing the newest kite answer and see what happens!

Thank you to all!

**Comment by hvasbath** [comment]
@Wilhelm-Berrocal because this is of the anaconda thing I wrote
Your python session gets started from the anaconda environment.
However, you installed kite to your system but not to the anaconda environment, because you have been using sudo.
So please also when you try installing the python3 version-DONT use sudo if you are using anaconda!!!

**Comment by Wilhelm-Berrocal** [comment]
@hvasbath Now I understand what I did, I installed Pyrocko and Kite following this instructions:

`sudo pip install git+https://github.com/pyqtgraph/pyqtgraph.git`
`sudo pip install git+https://github.com/pyrocko/kite.git`

To be used by the system Python `/usr/bin/python` which is Python 2, but since I work with Anaconda, Anaconda can´t find Kite, but strangely enough it can find Pyrocko, this makes me wonder what is happening; anyways after switching to the system Python 2 I can finally work with kite:

![scrot3](https://user-images.githubusercontent.com/8532837/40794810-e2a3a146-64c5-11e8-9053-63231dd23f56.png)

![scrot4](https://user-images.githubusercontent.com/8532837/40794947-36dca14a-64c6-11e8-8ca0-e69d8f7e68ae.png)

Now I will try to install the Python 3 version as @hsudha suggested.

Thank you for your help!

**Comment by Wilhelm-Berrocal** [comment]
Sorry, I mistakenly closed the tread. It´s open again

**Comment by Wilhelm-Berrocal** [comment]
Hello again! after several tries I was able to install Kite and use Talpa with the Okada model, now is time to learn how to use the software.

![scrot5](https://user-images.githubusercontent.com/8532837/40799065-34ac0a6c-64d2-11e8-9043-5fec2ef3ec57.png)

![scrot7](https://user-images.githubusercontent.com/8532837/40799080-3eba8a4c-64d2-11e8-8d47-297830bead9c.png)

Thank you all for your help!
