### ISSUE TITLE
Wrong geocoding of latitude of Gamma files

### ISSUE THREAD

**Issue by wsja** [pyrocko/kite#48]
In kite, when importing a Gamma file, the the corner latitude is computed from the number of columns of the interferogram, but it should be the number of lines.

Line 439 in scene_io.py must read:

c.frame.llLat = params['corner_lat'] + params['post_lat'] * nlines

instead of

c.frame.llLat = params['corner_lat'] + params['post_lat'] * nrows

(and nrows could be renamed to ncols, for clarity)

Cheers Wasja

**Comment by hsudha** [comment]
Oh, indeed! Thanks for finding that bug, Wasja! The fact that `nrows` is actually `ncols` must have induced the error. It is fixed now. Along with the same bug that crawled in the ROIPAC import of LatLon geocoded data.
Cheers, Henriette
