### ISSUE TITLE
Tool to click-mask a scene

### ISSUE THREAD

**Issue by wsja** [pyrocko/kite#52]
Hi,

I have a little script to mask a kite scene, i.e. set the displacement to `NaN` where there are for example unwrapping errors, using a matplotlib window and a matplotlibs `ginput()` method.

I would like to make this a method of  `BaseScene` but just wonder what would be the kite-way of doing so.

My idea is to add a method `BaseScene.click_mask()`. When the method is called, a matplotlib window opens, one clicks a polygon around the area to be masked, finishes with a double click and the Scene would be masked.

Now, when implementing this, I wonder whether I would directly set the `displacement` to `NaN` or rather set the `displacement_mask` to `True`? I'm right now doing the former, but would prefer the latter. However I don't understand why `displacement_mask` is implemented as it is. How would I set arbitrary elements to `True` without manipulating `displacement`?

**Comment by hsudha** [comment]
Hi, this is a very nice feature we were planning. Thanks for working on it! 
We'll come back with details. You figured out the purpose of the `displacement_mask` correctly. The plan is that one can always go back to the original status of the imported data.

**Comment by miili** [comment]
Hi Wasja,
that funtionality would really be great in Spool. The mechanism should be similar to the APS and GACOS module (see `dev` branch). That way we can easily apply and remove masks from the data.

We can use the region of interest tools from pyqtgraph. See `python3 -m pyqtgraph.examples` and check out the Region-of-Interest example.
So, this would require two modules: (1) a `scene_mask.py`, without GUI interaction, and (2) a Spool tab which handles the user GUI interaction. We can sit together and implement this, if you are interested.

Best,
Marius

**Comment by wsja** [comment]
I'd love to get started with the command-line tool. I need to have something up-and-running I can integrate in my workflow soon ... and would be happy if it is useful later on.

So, for the moment, I would implement my 10 lines of code in a `scence_mask.py` module and import it as a method of `Scene` (or something else?) in `scene.py`. There would be a matplotlib window popping up. This is the minimal GUI that the method requires, but of course if one is in the spool-frontend, this would instead be an extra tab.

@miili , I try to get this working for my own use case -- and let you know about any success. I'll call you to see if we can meet in the next two weeks.

Cheers, Wasja
