### ISSUE TITLE
scene reopening explotion of memory consumption

### ISSUE THREAD

**Issue by hvasbath** [pyrocko/kite#53]
Current dev branch
First, used spool to load and configure, subsample, APS correction, covariance calculation etc everything worked fine and very smooth and fast! Saved that to a kite scene.

Second, reopening the same saved scene in spool again seems impossible at least on my machine.
The logger spams "applying APS to displacment" as it seems to be in some loop
Memory consumption goes up from 1.8GB above 8GB fills the swap of 2GB and I have to reset and restart my computer to get control again.

I am lost where the loop is occuring, in the plugin_init.apply it loops only over all the available plugins which is just four ... maybe it somehow loops over quadtree leaves?

**Comment by miili** [comment]
Fixed in https://github.com/pyrocko/kite/commit/e9f70b7ff1e857af3e421bdfc3e618485fe0ca12
