### ISSUE TITLE
import bug

### ISSUE THREAD

**Issue by renierlgv** [pyrocko/kite#56]
Hello. 
I believe there is an import bug in the "covariance.py" code since fftpack is not an attribute of scipy but a subpackage. 
import scipy.fftpack after the scipy import line fixed it for my python/scipy versions.
Regards,
R

**Comment by hvasbath** [comment]
Please always post the FULL error traceback otherwise we wont be able to help or investigate. Also please post your scipy version. Thanks!

**Comment by miili** [comment]
scipy decided to rename `scipy.fftpack` to `scipy.fft`, we will support both. Thanks for reporting!
