### ISSUE TITLE
package structure makes editable installation fail

### ISSUE THREAD

**Issue by scottstanie** [pyrocko/kite#68]
I noticed that certain ways of installing kite worked fine for me, others failed.
For example, when I clone the repo and try to install a development version with `pip install -e .`:
```
$ git clone https://github.com/pyrocko/kite && cd kite
$ pip install -e .
```

It fails to create a link to the right package, and actually tries to install a package named "src":

```
(mapping) [scott@lidar kite-test]$ python
Python 3.8.5 | packaged by conda-forge | (default, Aug 29 2020, 01:22:49)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'kite'
>>> import src
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/scott/repos/kite/src/__init__.py", line 4, in <module>
    from .scene import Scene, TestScene, read  # noqa
  File "/home/scott/repos/kite/src/scene.py", line 17, in <module>
    from kite.quadtree import QuadtreeConfig
ModuleNotFoundError: No module named 'kite'
```

This is because the "kite.egg-link" file that it creates in the `site-packages` folder points to the repository root, and there's no "kite" folder to find.

```
(mapping) [scott@lidar ~]$ cat ~/miniconda3/envs/mapping/lib/python3.8/site-packages/kite.egg-link
/home/scott/repos/kite
.(mapping) [scott@lidar ~]$ ls /home/scott/repos/kite
build  CHANGELOG.md  docs  kite.egg-info  LICENSE.md  maintenance  README.md  requirements.txt  setup.cfg  setup.py  src  test
```

Some recent packaging guides suggest structuring the package like this one: https://github.com/pypa/sampleproject
```
<repository directory>
    /src/
        package_folder
```
i.e.
```
<repository directory>
    /src/
        kite/
           all the code that's currently in "src/"
```
https://packaging.python.org/tutorials/packaging-projects/#creating-the-package-files

while another (opinionated) guide suggests using the name of the package as the first-level folder https://docs.python-guide.org/writing/structure/#the-actual-module which would just involve renaming "src/" to "kite/"

```
<repository directory>
    /kite/
        all the code that's currently in "src/"
```

I tested this on my fork, and it only involves changing a couple lines from `src/` to `kite/` in the `setup.py`: https://github.com/scottstanie/kite/commit/ee3886b9eb3c8b015049d4a3abaf699fa6890a5c
```
$ python
Python 3.8.5 | packaged by conda-forge | (default, Aug 29 2020, 01:22:49)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kite
>>>
```

**Comment by miili** [comment]
This should be fixed in `v1.5.0`
