### ISSUE TITLE
Spool- error load npz related to self.image.scale

### ISSUE THREAD

**Issue by mgovorcin** [pyrocko/kite#90]
After updating to kite 1.5.2 version, I cannot start spool GUI by loading the prepared npz files. I am getting this error:

**File "/Users/govorcin/insar/miniconda3/envs/beat/lib/python3.8/site-packages/kite/spool/base.py", line 274, in transFromFrame
    self.image.scale(frame.dE, frame.dN)**

How to resolve this?

The full error message is: 
[log.txt](https://github.com/pyrocko/kite/files/9822800/log.txt)

The same input file worked with previous kite versions.  The input npz can be found here: https://drive.google.com/file/d/1pWe9rFHkAUrKjY8Wv_1dntpOwbQhd86N/view?usp=sharing 

My conda env:
[conda_list.txt](https://github.com/pyrocko/kite/files/9822928/conda_list.txt)

**Comment by jdaled** [comment]
I am encountering the same issue. Both on installation from source and in a conda environment. And using the sample L'Aquila data or my own data.

**Comment by hvasbath** [comment]
Can you please also state the OS you are using? I hope to reproduce this here locally.

**Comment by hvasbath** [comment]
The image object is from the pyqtgraph library. So I think it is related to versioning of pyqtgraph. I have version 0.12.4 and it works. Likely they changed sth upstream and you have newer versions than 0.12.4 ? Then we would need to update that in the requirements pyproject.toml here in KITE.

**Comment by jdaled** [comment]
> 

Indeed, my pyqtgraph is version 0.13.1 in my main system and in the conda environment, in Ubuntu.  Changing to version 0.12.4 makes spool work.

**Comment by hvasbath** [comment]
Pinging @miili , we need to fix pyproject.toml for pyqtgraph to be 0.12.4. Will make a PR ...

**Comment by miili** [comment]
Thanks, released v1.5.3
